# Generated by Django 2.2.4 on 2020-06-01 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cars',
            name='top_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='manufacturer', to='cars.Cars'),
        ),
    ]
